@startuml
participant "Client App" as ClientApp
participant "Game API" as GameAPI
participant "Game Database" as GameDatabase
participant "WebSocket Server" as WebSocketServer
ClientApp -> GameAPI : Join Game
GameAPI -> GameDatabase : Load game data
GameAPI -> GameDatabase : Validate permission to join game
GameAPI -> GameDatabase : Add player to game
GameAPI -> WebSocketServer: Push notification: Player Joined Game
GameAPI -> ClientApp : Return confirmation
@enduml