@startuml
participant "Client App" as ClientApp
participant "Game API" as GameAPI
participant "Game Database" as GameDatabase
participant "Game Start Queue" as GameStartQueue
participant "Game Engine" as GameEngine
participant "WebSocket Server" as WebSocketServer
ClientApp -> GameAPI : Start game
GameAPI -> GameDatabase : Validate permission\nto start game
GameAPI -> GameStartQueue : Add message: Game Start Requested
GameAPI -> ClientApp : Return confirmation
GameEngine -> GameStartQueue: Receive message
GameEngine -> GameDatabase: Load game data
GameEngine -> GameEngine: Start game
GameEngine -> WebSocketServer: Publish notification: Game Started
GameEngine -> GameStartQueue : Acknowledge message
@enduml